### ISSUE TITLE
merge the serie and work entity types

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#271]
* some works are constituted of mutliple parts that might have editions for themselves #99 
* series might have editions of the whole serie at once

The trickiest part I can think of is that the client will have to recursively check for parts of any works now?

**Comment by maxlath** [comment]
to fix once this is done:
* https://inventaire.io/entity/wd:Q1214163

**Comment by maxlath** [comment]
Merging works and series might create some new issues: searching for series (to autocomplete a value for wdt:P179) for instance, would now return any work? So if you try to add the latest Asterix album to the Asterix series (wd:Q42490) would compete against all the other Asterix Albums? This might be solved by the series popularity score being higher than its parts, but it's still, in 99% of the cases, crowding results with undesired suggestsions.

Maybe:
- point 1 could be solved with a "serie" type lock, cf https://github.com/inventaire/inventaire/issues/99#issuecomment-1771442071
- point 2 could be solved by allowing wdt:P629 to have values of both "work" and "serie" types

**Comment by maxlath** [comment]
A reason to keep the type distinction between "works known to have parts" aka "series" and "works not known to have parts" aka "works", is that in some cases it helps to prevent bad automatic edits. Example: see this error from the resolver:

```js
****** get_resolved_entry error ******
Error: invalid claim entity type: serie
    at error_.new (file:///home/admin/inventaire/server/lib/error/error.js:17:15)
    at verifyClaimEntityType (file:///home/admin/inventaire/server/controllers/entities/lib/validate_and_format_claim_value.js:76:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1) {
  statusCode: 400,
  context: [
    'wd:Q3665579',
    entry: {
      edition: {
        isbn: '9784063722871',
        claims: {
          'wdt:P1476': [ 'チェーザレ : 破壊の創造者' ],
          'wdt:P648': [ 'OL27121119M' ],
          'wdt:P407': [ 'wd:Q5287' ],
          'wdt:P1104': [ 139 ],
          'wdt:P1680': [ 'Il creatore che ha distrutto' ],
          'wdt:P577': [ '2007' ],
          'wdt:P123': [ 'wd:Q726081' ]
        },
        labels: {},
        resolved: false
      },
      works: [
        {
          uri: 'wd:Q3665579',
          claims: { 'wdt:P648': [ 'OL19940640W' ] },
          labels: {},
          resolved: true
        }
      ],
      authors: [
        {
          labels: { en: 'Fuyumi Sōryō' },
          claims: { 'wdt:P648': [ 'OL6576435A' ] },
          uri: 'wd:Q469923',
          resolved: true
        }
      ]
    }
  ],
  emitter: [
    'Error: invalid claim entity type: serie',
    'verifyClaimEntityType file:: server/controllers/entities/lib/validate_and_format_claim_value.js:76:21',
    'process.processTicksAndRejections node:internal/process/task_queues:95:5',
    'async Promise.all index 1',
    'async default file:: server/controllers/entities/lib/validate_and_format_claim_value.js:35:3'
  ]----
}
```

This edition/work/author entities auto-creation fails because OpenLibrary points to a serie (`wd:Q3665579`) as the edition work, while the right work should be a volume from that serie. Having the type distinction here helped to enter wrong data.

**Comment by maxlath** [comment]
More reasons to not fully merge series into works: https://github.com/inventaire/inventaire/issues/711 https://github.com/inventaire/inventaire/issues/715
