### ISSUE TITLE
revert-merge crash: Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire#439]
server logs (`Oct 27 12:35:56`):
```
****** inverse patch 582c0644d0a9c06d4758deb86dfc388b:4 ******
[
  {
    op: 'add',
    path: '/claims/wdt:P50/1',
    value: 'inv:80ad2bc4c59713a69196f5cecb169949',
    context: undefined
  },
  {
    op: 'test',
    path: '/claims/wdt:P50/0',
    value: 'wd:Q87777498',
    context: undefined
  },
  { op: 'remove', path: '/claims/wdt:P50/0', context: undefined }
]
-----
****** Cannot read property 'indexOf' of undefined ******
[
  "TypeError: Cannot read property 'indexOf' of undefined",
  '    at test (server/models/patch.js:147:46)',
  '    at server/models/patch.js:113:28',
  '    at Array.forEach (<anonymous>)',
  '    at applyInversePatch (server/models/patch.js:96:16)',
  '    at Object.revert (server/models/patch.js:65:24)',
  '    at revertFromPatchDoc (server/controllers/entities/lib/revert_edit.js:9:28)',
  '    at runMicrotasks (<anonymous>)',
  '    at processTicksAndRejections (internal/process/task_queues.js:94:5)',
  '    at async Promise.all (index 0)',
  '    at async module.exports (server/controllers/entities/lib/revert_merge.js:28:3)'
]
PUT /api/entities?action=revert-merge 500 2340.836ms
```

the line that crashes https://github.com/inventaire/inventaire/blob/4047c40/server/models/patch.js#L147

**Comment by maxlath** [comment]
could it be that it was just that those works had been edited since the initial merge, and that the reverse patch could not be applied? see also #440

**Comment by Aethelflaed** [comment]
It's possible I editing these works between the merge and the revert-merge indeed
