### ISSUE TITLE
Deploying documentation request

### ISSUE THREAD

**Issue by niamtokik** [inventaire/inventaire#59]
Hi everyone,

I'm using FreeBSD (10.1) and OpenBSD (5.8), and I have some trouble with inventaire. What kind of system are you using for this app? I've not found any documentation about this software concerning implementation, testing or dev... Do you have any? :)

Here all the steps (I assume your server/workstation use OpenZFS and you can use jail):

``` sh
REPO="http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/10.1-RELEASE"
JAIL_OPTS="ip4=inherit ip6=inherit nopersist allow.raw_sockets 
  allow.set_hostname allow.socket_af allow.sysvipc
  exec.start='/bin/sh /etc/rc'"
YOUR_USER=inventaire

# create a dedicated dataset
zfs create tank/jails/inventaire.io

# get freebsd sources
cd /tank/jails/inventaire.io
for i in base lib32
do
  fetch ${REPO}/${i}.txz
  tar zxvfp ${i}.txz
done

# initialize resolv.conf
echo "nameserver 8.8.8.8" >> etc/resolv.conf

# do zfs snapshot for current state
zfs snapshot tank/jails/inventaire.io@begin

# start the jail and get a prompt
jail -c path=/tank/jails/inventaire.io name=inventaire ${JAIL_OPTS}
jexec inventaire sh

# here init pkg & cie
pkg << EOF
y
EOF

# bash and untar are needed...
pkg install node npm git untar

# add standard user 
adduser ${YOUR_USER}

# initialize user env
# I think its the more useful parts of the script,
# and this part is the same on other OS...
su - ${YOUR_USER}
mkdir src
cd src
git clone https://github.com/inventaire/inventaire-client
git clone https://github.com/inventaire/inventaire

# try to install inventaire
cd inventaire
npm install.
```

Here the output of the last command:

```
\
> inventaire@2.1.0 postinstall /usr/home/inventaire/src/inventaire
> ./scripts/postinstall


> inventaire@2.1.0 patches /usr/home/inventaire/src/inventaire
> ./scripts/run_patches ./scripts/patches

patch-tools initialized
looking for patches in folder: ./scripts/patches
-------------------------
cat: /home/inventaire/inventaire/node_modules/americano/main.js: No such file or directory
sed: 1: "/home/inventaire/inventair ...": extra characters at the end of n command
sed: 1: "/home/inventaire/inventair ...": extra characters at the end of n command
main.js: patched!
-------------------------
patches done!
trying to clone git clone -b i18n https://github.com/inventaire/inventaire.git ./server/lib/emails/i18n/src
Cloning into './server/lib/emails/i18n/src'...
remote: Counting objects: 8671, done.
remote: Total 8671 (delta 0), reused 0 (delta 0), pack-reused 8671
Receiving objects: 100% (8671/8671), 1.10 MiB | 702.00 KiB/s, done.
Resolving deltas: 100% (6070/6070), done.
Checking connectivity... done.
Error: Cannot find module '/usr/home/inventaire/src/inventaire/client/app/lib/handlebars_helpers/linkify'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.module.exports.require (/usr/home/inventaire/src/inventaire/config/universal_path.coffee:55:28)
  at Object.<anonymous> (/usr/home/inventaire/src/inventaire/server/lib/emails/i18n/src/lib/find_keys.coffee:4:14)
  at Object.<anonymous> (/usr/home/inventaire/src/inventaire/server/lib/emails/i18n/src/lib/find_keys.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/usr/home/inventaire/src/inventaire/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/home/inventaire/src/inventaire/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/usr/home/inventaire/src/inventaire/server/lib/emails/i18n/src/lib/extend_lang_with_default.coffee:3:12)
  at Object.<anonymous> (/usr/home/inventaire/src/inventaire/server/lib/emails/i18n/src/lib/extend_lang_with_default.coffee:1:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/usr/home/inventaire/src/inventaire/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/home/inventaire/src/inventaire/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/usr/home/inventaire/src/inventaire/server/lib/emails/i18n/src/generate_lang_json.coffee:13:25)
  at Object.<anonymous> (/usr/home/inventaire/src/inventaire/server/lib/emails/i18n/src/generate_lang_json.coffee:9:1)
  at Module._compile (module.js:413:34)
  at Object.exports.r
> inventaire@2.1.0 update-git-hooks /usr/home/inventaire/src/inventaire
> ./scripts/update_git_hooks

git hooks updated
nodemailer@1.9.0 node_modules/nodemailer
nodemailer-smtp-transport@1.1.0 (nodemailer-wellknown@0.1.7, clone@1.0.2, smtp-connection@1.3.8)
nodemailer-direct-transport@1.1.0 (smtp-connection@1.3.8)
libmime@1.2.0 (libbase64@0.1.0, libqp@1.1.0, iconv-lite@0.4.13)
needle@0.11.0 (iconv-lite@0.4.13, debug@2.2.0)
```

Many thanks in advance. :)

**Comment by maxlath** [comment]
hi!
Indeed, deployment lacks documentation.

So far, I only installed it on Ubuntu 12.04>15.10 machines, and didn't test on any other environment.

Also, some installation scripts are tightly coupled with my own setup: some scripts such as [`run_patches`](https://github.com/inventaire/inventaire/blob/master/scripts/run_patches#L20) expect the project root to be a folder in `$HOME`: I think this is what produced the file path `/home/inventaire/inventaire/node_modules/americano/main.js` which doesn't seem to make sense in your setup.

Could the trailing dot at the last line of your script (`npm install.`) be responsible of some errors too?

I created a [Wiki page on Deployment](https://github.com/inventaire/inventaire/wiki/Deployment), feel welcome to improve!

**Comment by niamtokik** [comment]
Oh! Thanks for the wiki page! I will check that... Maybe create some process for deploying it on *BSD and other linux like.

Thanks :)

**Comment by niamtokik** [comment]
> Could the trailing dot at the last line of your script (npm install.) be responsible of some errors too?

Nope, same error. I guess its due to a missing part of linkify app (but, I don't know why currently) ;)

**Comment by niamtokik** [comment]
ok, I've forked your [git repo](https://github.com/niamtokik/inventaire/tree/dev) and I'm working on it. Currently, all seems good, and `npm start`, start the app but I have a blank page. Do you have an idea why (on linux and freebsd)?

**Comment by maxlath** [comment]
@niamtokik do you have some logs in the server or in the browser console that could help?

Once your server and couchdb are running, a few commands could help identify where the problem comes from:

```bash
curl http://localhost:3006/api/tests/public
# should return {"server":"GET OK"

curl http://localhost:3006/api/items/public?action=last-public-items
# should return {"users":[], "items": []}
# confirming that CouchDB is OK

curl http://localhost:3006/whatever
# should return [index.html](https://github.com/inventaire/inventaire-client/blob/master/app/assets/index.html)
# confirming that the client correctly initialized
```

**Comment by niamtokik** [comment]
## Linkify Issue

Nope. Its seems some npm deps was not compatible with arm and cannot be build on it. On amd64/i386, no more issue. I have some others small crappy errors.

## CouchDB issues

I'm working on it. But one issue was to create a dedicated user with not enough privilege. I was not thinking about that, and inventaire.io need administrator right on couchdb instace (need to create design, view and others things like that).

Concerning security, its important to have one user dedicated to one task (or some tasks). I don't like using one administrator user on one database used by one (or many) softs. I will work on that coming days.

## Blank page

My real issue currently is the "blank page" after successful install. When I use http://127.0.0.1:3006, I have a single blank page with header and small body but... empty.

Here the page generated:

``` html
<!doctype html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Inventaire - your friends and communities are your best library</title>
  <meta name="keywords" content="inventory, inventaire, open knowledge, resources mapping, books, sharing" />
  <meta name="viewport" content="width=device-width">
  <meta name="fragment" content="!">

  <link rel="stylesheet" href="/public/stylesheets/vendor.css?9539afc">
  <link rel="stylesheet" href="/public/stylesheets/app.css?9539afc">
  <script src="/public/javascripts/vendor.js?9539afc"></script>
  <script src="/public/javascripts/app.js?9539afc"></script>
  <script>require('initialize');</script>

  <link rel="canonical" href="https://inventaire.io/" />
  <link rel="sitemap" href="/public/sitemaps/sitemapindex.xml" />

  <!-- TWITTER -->
  <meta name="twitter:title" content="Inventaire - your friends and communities are your best library">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@inventaire_io">
  <meta name="twitter:description" content="Make the inventory of your books and mutualize with your friends and communities into an infinite library!">
  <meta name="twitter:image" content="https://inventaire.io/img/862142ffb58f4950f9f567c3ef72a90b0c79badc.jpg">

  <!-- FACEBOOK -->
  <meta property="fb:app_id" content="1383915125249576"/>
  <meta property="og:site_name" content="Inventaire">
  <meta property="og:url" content="https://inventaire.io/">
  <meta property="og:title" content="Inventaire - your friends and communities are your best library">
  <meta name="description" property="og:description" content="Make the inventory of your books and mutualize it with your friends and communities into an infinite library!" />
  <!-- limiting to one og:image to be sure it's the one selected. cf http://stackoverflow.com/questions/13424780/facebook-multiple-ogimage-tags-which-is-default -->
  <meta property="og:image" content="https://inventaire.io/img/862142ffb58f4950f9f567c3ef72a90b0c79badc.jpg">
  <!-- og:locale and og:locale:alternate will be added by general/lib/document_lang -->

  <link rel="apple-touch-icon" sizes="57x57" href="/public/images/icon/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/public/images/icon/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/public/images/icon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/public/images/icon/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/public/images/icon/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/public/images/icon/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/public/images/icon/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/public/images/icon/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/public/images/icon/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="/public/images/icon/favicon-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="/public/images/icon/favicon-160x160.png" sizes="160x160">
  <link rel="icon" type="image/png" href="/public/images/icon/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="/public/images/icon/favicon-16x16.png" sizes="16x16">
  <link rel="icon" type="image/png" href="/public/images/icon/favicon-32x32.png" sizes="32x32">
  <meta name="msapplication-TileColor" content="#172c41">
  <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  <link rel="search" type="application/opensearchdescription+xml" href="/public/opensearch.xml" title="Inventaire Search" />
  <script type="application/ld+json">ACTIONS</script>

  <!-- updated by general/lib/document_lang -->
  <link rel="alternate" href="https://inventaire.io/" hreflang="en" />
  <link rel="alternate" href="https://inventaire.io/?lang=fr" hreflang="fr" />
  <link rel="alternate" href="https://inventaire.io/?lang=de" hreflang="de" />
  <link rel="alternate" href="https://inventaire.io/?lang=sv" hreflang="sv" />
  <link rel="alternate" href="https://inventaire.io/?lang=es" hreflang="es" />
  <link rel="alternate" href="https://inventaire.io/?lang=pl" hreflang="pl" />
</head>
<body>
<div id="app">
  <div class="booting">
    <i class="fa fa-spinner fa-pulse fa-3x"></i>
  </div>
</div>
<div id="legacy">
  <form id="browserLogin" method="post" action="/api/auth/public?action=submit" onclick="false" autocomplete="on">
    <input type="text" name="username" id="browserUsername" />
    <input type="password" name="password" id="browserPassword"/>
    <input type="text" name="strategy" value="local" />
    <button type="submit"></button>
  </form>
</div>
<!-- PIWIK -->
</body>
</html>
```

and the logs:
```
$ npm start

> inventaire@2.1.0 start /usr/home/inventaire/inventaire
> coffee server.coffee

env: default
port: 3006
host: localhost
****** fullHost ******
http://localhost:3006
-----
geo openned
geo openned
meta openned
cache openned
****** prerender access restriction disabled ******
{ ip: null, quota: 500 }
-----
analytics openned
[2016-02-18 07:57:20:587] info - americano | Routes loaded.
mailer disabled
activity summary disabled
[2016-02-18 07:57:20:627] info - americano | Configuration for development loaded.
inventaire server is listening on port 3006...
logs archived
****** users last seq ******
0
-----
usersDB ready!
startup: 4512.428ms
entitiesDB ready!
notificationsDB ready!
transactionsDB ready!
analyticsDB ready!
itemsDB ready!
commentsDB ready!
[Thu Feb 18 2016 07:57:50 GMT] logged in 0 / total 0
****** analytics transfered to Couchdb ******
{ transfered: 0, kept: 0, dropped: 0, refTime: 1455782260569 }
-----
GET / 200 15.501 ms - 5124
GET /public/stylesheets/vendor.css?9539afc 200 8.819 ms - 5124
GET /public/stylesheets/app.css?9539afc 200 10.437 ms - 274550
GET /public/javascripts/vendor.js?9539afc 200 8.224 ms - 290555
GET /public/javascripts/app.js?9539afc 200 5.155 ms - 571524
GET /public/fonts/AlegreyaSans-Regular.ttf 200 2.025 ms - 119016
GET /public/images/icon/favicon-192x192.png 200 1.099 ms - 5078
GET /public/images/icon/favicon-160x160.png 200 1.179 ms - 4041
GET /public/images/icon/favicon-16x16.png 200 1.013 ms - 577
GET /public/images/icon/favicon-32x32.png 200 0.969 ms - 890
GET /public/images/icon/favicon-32x32.png 200 1.327 ms - 890
GET / 200 4.074 ms - 5124
```

 * all reference to https://inventaire.io. If someone use another domain, how can I change that?
 * when I use `http://127.0.0.1:3006/api/auth/public?action=submit` I have this result `{"status_verbose":"GET isnt implemented on this route"}`
 * I've not set reverse proxy (apache, nginx...) on it

Here the debug log with `DEBUG=express:* coffee server.coffee`:

```
$ DEBUG=express:* coffee server.coffee
env: default
port: 3006
host: localhost
****** fullHost ******
http://localhost:3006
-----
  express:application compile etag weak +0ms
  express:application compile query parser extended +2ms
  express:application compile trust proxy false +2ms
  express:application booting in development mode +1ms
geo openned
geo openned
meta openned
  express:router use / query +2s
  express:router:layer new / +1ms
  express:router use / expressInit +1ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:router use / bodyParser +0ms
  express:router:layer new / +0ms
  express:router use / methodOverride +1ms
  express:router:layer new / +0ms
  express:router use / errorHandler +0ms
  express:router:layer new / +0ms
  express:router use / logger +0ms
  express:router:layer new / +0ms
  express:router use /public serveStatic +0ms
  express:router:layer new /public +0ms
  express:router use / favicon +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +1ms
  express:router use / cookieParser +0ms
  express:router:layer new / +0ms
  express:router use / _cookieSession +0ms
  express:router:layer new / +0ms
  express:router use / initialize +0ms
  express:router:layer new / +0ms
  express:router use / authenticate +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +1ms
  express:router:layer new / +0ms
cache openned
****** prerender access restriction disabled ******
{ ip: null, quota: 500 }
-----
analytics openned
  express:router:route new /log/i18n +2s
  express:router:layer new /log/i18n +0ms
  express:router:route post /log/i18n +1ms
  express:router:layer new / +0ms
  express:router:route new /local/* +0ms
  express:router:layer new /local/* +0ms
  express:router:route get /local/* +0ms
  express:router:layer new / +0ms
  express:router:route new /api/auth +0ms
  express:router:layer new /api/auth +0ms
  express:router:route get /api/auth +0ms
  express:router:layer new / +0ms
  express:router:route new /api/auth +0ms
  express:router:layer new /api/auth +1ms
  express:router:route post /api/auth +0ms
  express:router:layer new / +0ms
  express:router:route new /api/auth/public +0ms
  express:router:layer new /api/auth/public +0ms
  express:router:route get /api/auth/public +0ms
  express:router:layer new / +0ms
  express:router:route new /api/auth/public +0ms
  express:router:layer new /api/auth/public +0ms
  express:router:route post /api/auth/public +0ms
  express:router:layer new / +0ms
  express:router:route new /api/auth/public/token +0ms
  express:router:layer new /api/auth/public/token +0ms
  express:router:route get /api/auth/public/token +0ms
  express:router:layer new / +0ms
  express:router:route new /api/user +1ms
  express:router:layer new /api/user +0ms
  express:router:route get /api/user +0ms
  express:router:layer new / +0ms
  express:router:route new /api/user +0ms
  express:router:layer new /api/user +0ms
  express:router:route put /api/user +0ms
  express:router:layer new / +0ms
  express:router:route new /api/user +0ms
  express:router:layer new /api/user +0ms
  express:router:route delete /api/user +0ms
  express:router:layer new / +0ms
  express:router:route new /api/users/public +0ms
  express:router:layer new /api/users/public +0ms
  express:router:route get /api/users/public +1ms
  express:router:layer new / +0ms
  express:router:route new /api/users +0ms
  express:router:layer new /api/users +0ms
[...]
[2016-02-18 08:17:09:184] info - americano | Routes loaded.
mailer disabled
activity summary disabled
[2016-02-18 08:17:09:218] info - americano | Configuration for development loaded.
inventaire server is listening on port 3006...
logs archived
****** users last seq ******
0
-----
itemsDB ready!
startup: 4881.415ms
entitiesDB ready!
transactionsDB ready!
analyticsDB ready!
notificationsDB ready!
usersDB ready!
commentsDB ready!
```

FYI, CouchDB is running well. ;)

## Documentation

Concerning deployment documentation, I've tested past days inventaire.io installation process on some systems:

 * [FreeBSD 10.1](https://www.freebsd.org/releases/10.1R/announce.html), amd64 (work but blank page)
 * [Void-Linux](http://www.voidlinux.eu/), armv7 (doesn't work, npm module dep error during build)
 * [Void-Linux](http://www.voidlinux.eu/), amd64 (work but blank page)
 * [OpenBSD 5.8](http://www.openbsd.org/58.html), i386 (work in progress)
 * [OpenBSD 5.8](http://www.openbsd.org/58.html), amd64 (work in progress)
 * [NetBSD 7.0](https://www.netbsd.org/releases/formal-7/NetBSD-7.0.html), amd64 (not tested yet)
 * Ubuntu 14.04, amd64 (not tested yet)

I will prepare also some method for ease of deployment and security (FreeBSD+jails, Linux+LxC, NetBSD+rump, docker, vagrant...).

If you want to see my work, you can read it from my inventaire fork (https://github.com/niamtokik/inventaire/tree/dev/doc/deployment).

**Comment by maxlath** [comment]
Everything seems fine in the server logs, I guess the issue either comes from those issues with the dependencies or from a fail in the client build, which unfortunately happens quite frequently. This could hopefully be fixed by attempting to rebuild the client:
```bash
# from project root
cd client
./node_modules/brunch/bin/brunch watch
# or simply "npm start" if brunch is installed globally
```
Client build errors should let a big ugly error message in the browser console logs, could you have a look at those? Logs are disabled by default, 2 options to activate them
* from the url: `http://127.0.0.1:3006?debug=true`
* from the console: `localStorage.setItem('debug', true)`

<hr>
`{"status_verbose":"GET isnt implemented on this route"}` is just a [placeholder for routes without](https://github.com/inventaire/inventaire/blob/master/server/controllers/routes.coffee#L30), supposed to give a hint that a POST was probably expected, which is indeed the case for `/api/auth/public?action=submit`

Thank you for all this! I should have more time in the coming weeks to dig on those issues and improve the documentation

**Comment by niamtokik** [comment]
Yeap, I have one error with client (you could look at debug output on [pastebin](http://pastebin.com/KPxEYKRT))

```
$ ./node_modules/brunch/bin/brunch watch
18 Feb 12:34:40 - error: [Error: Component JSON file "/usr/home/inventaire/inventaire/client/bower_components/blueimp-canvas-to-blob/.bower.json" must have `main` property. See https://github.com/paulmillr/read-components#README]
18 Feb 12:34:43 - info: compiling
18 Feb 12:34:47 - info: compiling.
18 Feb 12:34:50 - info: compiled 452 files into 3 files, copied 42 in 11.2 sec
```

After using this command, brunch seems to be frozen and need to be killed (sigterm <3).

Concerning debug activation, this URL return the same blank page. Perhaps missed something?

``` sh
curl http://127.0.0.1:3006?debug=true
```

No problem! I hope this great idea will grow in near future... Clearly, I want to use it for one of my project! So if you need hand for security/sysadmin/netadmin, I can help you! ;)

**Comment by maxlath** [comment]
well, `debug=true` is meant to trigger actions in the heavy javascript client so it won't have any effect from curl, only from a browser that would have fetched and executed
```
  <script src="/public/javascripts/vendor.js?9539afc"></script>
  <script src="/public/javascripts/app.js?9539afc"></script>
```

<hr>

for the blueimp-canvas-to-blob bug during brunch compilation, this commit should solve it https://github.com/inventaire/inventaire-client/commit/30b59fe

<hr>

Your help is very welcome! Very much looking forward to learn more about this project of yours! Feel free to open issues or just to reach me by email :) If you haven't yet, having a look at the [roadmap](https://trello.com/b/0lKcsZDj/inventaire-roadmap) could be of interest!

**Comment by maxlath** [comment]
deployment documentation is now in https://github.com/inventaire/inventaire-deploy/

**Comment by jum-s** [comment]
deployment/production documentation is now in https://git.inventaire.io/inventaire/tree/main/docs
